{
 "title": "kalu.solutions! ticker: [KALU]",
 "description": "kalu.solutions Stakepool Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Key rotation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_currentKESPeriod_int",
     "legendFormat": "Current period"
    },
    {
     "expr": "cardano_node_Forge_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry period"
    },
    {
     "expr": "cardano_node_Forge_metrics_remainingKESPeriods_int",
     "legendFormat": "KES Periods left"
    },
    {
     "expr": "(cardano_node_Forge_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "Days left"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int{alias=\"core\"}",
     "legendFormat": "Bore"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int{alias=\"core\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 2, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"core\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forged_int{alias=\"core\"} / cardano_node_metrics_Forge_node_is_leader_int{alias=\"core\"} * 100)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Core Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"core\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"core\"} / (node_memory_MemTotal_bytes{alias=\"core\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"core\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"core\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_active_stake / 1000000"
    }
   ]
  },
  {
   "title": "Live Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_total_stake / 1000000" }
   ]
  },
  {
   "title": "Rewards",
   "type": "stat",
   "description": "Current Epoch",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_rewards_epoch" }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"core\"}"
    }
   ]
  },
  {
   "title": "Relay1 System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relay1\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay1\"} / (node_memory_MemTotal_bytes{alias=\"relay1\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay1\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Relay 2 System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relay2\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay2\"} / (node_memory_MemTotal_bytes{alias=\"relay2\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay2\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay2\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Blocks Estimated",
   "type": "stat",
   "description": "Current Epoch",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_blocks_estimated" }
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "description": "Current Epoch",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_blocks_epoch" }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_delegators" }
   ]
  },
  {
   "title": "Available RAM (Core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=\"core\"}"
    }
   ]
  },
  {
   "title": "Uptime Core-Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"core\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Available RAM (Relay1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=\"relay1\"}"
    }
   ]
  },
  {
   "title": " Uptime Relay-Server1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"relay1\"})"
    }
   ]
  },
  {
   "title": "Available RAM (Relay2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=\"relay2\"}"
    }
   ]
  },
  {
   "title": " Uptime Relay-Server2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"relay2\"})"
    }
   ]
  },
  {
   "title": "System Load (core node)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"core\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"core\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"core\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relay1\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relay1\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relay1\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relay2\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relay2\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relay2\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Available Mem (Core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{alias=\"core\", mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime Core-Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns{alias=\"core\"} / (1000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Available Mem (Relay1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{alias=\"relay1\", mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime Relay-Node1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns{alias=\"relay1\"} / (1000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Available Mem (Relay 2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{alias=\"relay2\", mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime Relay-Node 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns{alias=\"relay2\"} / (1000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"core\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Relay1 TX's processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay1\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Relay2 TX's processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay2\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"core\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"core\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"core\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relay1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relay1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relay1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relay2\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relay2\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relay2\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Peers (Core)",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers (Relay1)",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers (Relay2)",
   "type": "stat",
   "description": "Connected peers to/from Relay 2",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers (Core Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connected Peers (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core node block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int{alias=\"core\"}[150s]) *60",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Relay 1 node block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int{alias=\"relay1\"}[150s]) *60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 node block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int{alias=\"relay2\"}[150s]) *60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (Core Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"core\"} / (node_memory_MemTotal_bytes{alias=\"core\"})))* 100",
     "legendFormat": "core"
    }
   ]
  },
  {
   "title": "Memory Utilization (Relay 1)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay1\"} / (node_memory_MemTotal_bytes{alias=\"relay1\"})))* 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (Relay 2)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay2\"} / (node_memory_MemTotal_bytes{alias=\"relay2\"})))* 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node peak memory allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 1 peak memory allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 peak memory allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Core Node)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Relay 1)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Relay 2)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node current \"residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"core\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 1 current \"residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay1\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 current \"residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay2\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"core\"}[1h])) * 3600",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Relay 1 Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relay1\"}[1h])) * 3600",
     "legendFormat": "relay1"
    }
   ]
  },
  {
   "title": "Relay 2 Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relay2\"}[1h])) * 3600",
     "legendFormat": "relay2"
    }
   ]
  },
  {
   "title": "Core Node max \"residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"core\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 1 max \"residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay1\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 max \"residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay2\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 1 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"relay2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node RSS (allocated memory in RAM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int{alias=\"core\"}*4096)/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 1 RSS (allocated memory in RAM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int{alias=\"relay1\"}*4096)/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 RSS (allocated memory in RAM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int{alias=\"relay2\"}*4096)/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Node available Disk Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{alias=\"core\", mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 1 available Disk Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{alias=\"relay1\", mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 available Disk Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{alias=\"relay2\", mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}